### ISSUE TITLE
wb label q5

### ISSUE THREAD

**Issue by WolfgangFahl** [maxlath/wikibase-cli#162]
- wikibase-cli version: 
```bashwb --version
16.1.1
```
- OS version:
```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
```
wb label q5
```
This is just a typo and shouldn't do much harm in fact i get:
```
node:9678) UnhandledPromiseRejectionWarning: Error: invalid id
    at Object.new (/usr/local/lib/node_modules/wikibase-cli/lib/errors.js:5:17)
    at input (/usr/local/lib/node_modules/wikibase-cli/lib/tolerant_id_parser.js:33:20)
    at Array.map (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/wikibase-cli/lib/entity_data_parser.js:25:24)
    at module.exports.attribute (/usr/local/lib/node_modules/wikibase-cli/lib/entity_attribute_command.js:19:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/wikibase-cli/bin/wb-label:2:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
(node:9678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9678) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Which is not a very helpful message to point to the fact that:
```bash
wb label Q5
human
```
works just fine

**Comment by maxlath** [comment]
Fixed in `v16.1.2`
