### ISSUE TITLE
Docker container's node is too old node, "ReferenceError: fetch is not defined"

### ISSUE THREAD

**Issue by mariushoch** [maxlath/wikibase-cli#190]
The docker container seems to be using an old node version, that lacks `fetch` (this is still true as of version [18.3.1](https://hub.docker.com/layers/maxlath/wikibase-cli/18.3.1/images/sha256-c0a130fa12e0f50c1a3abdae3f36cb7b2f1d6c8e282bd0fa2bdc9de3c5db6c56?context=explore)). All requests fail with `ReferenceError: fetch is not defined`. For details see below:

```lang=shell
$ podman run --rm -ti maxlath/wikibase-cli:17.0.10 label Q5 -i https://www.wikidata.org
[…]
human
```

```lang=shell
$ podman run --rm -ti maxlath/wikibase-cli:18.0.0 label Q5 -i https://www.wikidata.org
[…]
file:///usr/local/lib/node_modules/wikibase-cli/lib/request.js:14
  return fetch(url, options)
  ^

ReferenceError: fetch is not defined
    at request (file:///usr/local/lib/node_modules/wikibase-cli/lib/request.js:14:3)
    at get (file:///usr/local/lib/node_modules/wikibase-cli/lib/request.js:18:21)
    at entityDataParser (file:///usr/local/lib/node_modules/wikibase-cli/lib/entity_data_parser.js:39:22)
    at async entityAttributeCommand (file:///usr/local/lib/node_modules/wikibase-cli/lib/entity_attribute_command.js:26:3)
```

**Comment by maxlath** [comment]
Thanks for reporting! That should be fixed now in the latest image (and should not happen in the future, thanks to 9a04916)

**Comment by mariushoch** [comment]
It's indeed working now! Thanks a lot :)

```lang=shell
$ podman run --rm -ti maxlath/wikibase-cli --version
18.3.1
$ podman run --rm -ti maxlath/wikibase-cli label Q5 -i https://www.wikidata.org
Config file not found at /root/.config/wikibase-cli/config.json. Create? y/N y
human
```
