### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by almereyda** [maxlath/wikibase-cli#46]
After following [an ominuous link](https://github.com/maxlath/wikidata-cli/blob/0c24ffde655d20de3c2d9308a83db07d744ebe12/docs/write_operations.md#wd-edit-item) in the documentation and recreating a JSON following [the example](https://github.com/maxlath/wikidata-edit/blob/master/docs/how_to.md#edit-entity) as of q224.json as

```
{
  "id": "Q224",
  "claims": {
    "P4": "Q6",
    "P8": "Q218"
  }
}
```

with a valid configuration for a custom Wikibase instance, a stacktrace is thrown:

```
~/.tmp $ wd edit-item q224.json
TypeError: Cannot read property 'type' of undefined
    at module.exports.propertyId (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/properties/find_datatype.js:24:55)
    at module.exports (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/build_claim.js:9:20)
    at obj.(anonymous function).values.map.value (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/format.js:40:39)
    at Array.map (native)
    at /home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/format.js:40:26
    at Array.reduce (native)
    at Object.claims (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/format.js:22:32)
    at module.exports.data (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/validate_and_format_data.js:31:33)
    at err (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/edit.js:17:22)
    at _validateAndFormatData (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/edit.js:15:10)
    at data (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/node_modules/wikidata-edit/lib/entity/edit.js:7:12)
    at cmd (/home/ya/.nvm/versions/node/v6.9.4/lib/node_modules/wikidata-cli/lib/edit/edit_command.js:38:50)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by maxlath** [comment]
this is an [issue with custom instances and `wikidata-edit` as documented here](https://github.com/maxlath/wikidata-edit/blob/master/docs/how_to.md#custom-wikibase-instance), which isn't addressed from `wikidata-cli` yet

**Comment by maxlath** [comment]
there are actually two different problems here:
- `wikidata-edit` (on which all `wikidata-cli` write features are built) [relies heavily on the capacity to check properties datatype](https://github.com/maxlath/wikidata-edit/search?utf8=%E2%9C%93&q=find_datatype&type=), which is done by [having a list of those properties at hand](https://github.com/maxlath/wikidata-edit/blob/master/lib/properties/properties.js). This can be customized, but [the workflow isn't very satisfying yet](https://github.com/maxlath/wikidata-edit/blob/master/docs/how_to.md#custom-wikibase-instance)
- but to do this customization, you need a SPARQL endpoint, which all Wikibase don't have

**Comment by almereyda** [comment]
We do have such a SPARQL endpoint. What can I do to support mitigating this
infrastructural change, as it proposedly affects multiple repositories?

And to illustrate my suprise about properties having a type. Where are
these documented and coming from? Why are those not within each Wikibase's
namespace (P & Q) ?

I am wondering why these types are hardcoded, because I feel this is
working against Linked Data principles here, excluding the schema of the
data from its own representation.

**Comment by maxlath** [comment]
I don't know the internals of Wikibase, but a type is associated to each property, [as you can see in this query](https://query.wikidata.org/#SELECT%20%3Fproperty%20%3FpropertyLabel%20%3FpropertyType%0AWHERE%20%7B%0A%20%20%3Fproperty%20a%20wikibase%3AProperty%20.%0A%20%20%3Fproperty%20wikibase%3ApropertyType%20%3FpropertyType%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20ASC%28xsd%3Ainteger%28STRAFTER%28STR%28%3Fproperty%29%2C%20%27P%27%29%29%29%0ALIMIT%20100), which links to [this page where those types seem to be defined](http://wikiba.se/ontology-1.0.owl)

**Comment by maxlath** [comment]
so if you make this same query but specifying the customized SPARQL endpoint, isn't it working?
```sh
wd edit-item q224.json --instance http://some/wikibase/instance/w/api.php --sparql-endpoint http://some/sparql/endpoint
```

**Comment by almereyda** [comment]
Yes, I managed to mass-add items and translations with the flag after the
patch had been provided. Let me find the sources as a proof ...

**Comment by maxlath** [comment]
since `wikibase-edit@v3.0.0`, the map of properties datatype is generated by requesting the Wikibase server instead of relying on a possible SPARQL endpoint, making this all class of errors disappear \o/  `wikibase-edit` will be updated to `>v3.0.0` in the very soon coming `v8.0.0`
